### ISSUE TITLE
expects 'command' in input not 'arguments'

### ISSUE THREAD

**Issue by hmoffatt** [qdewaghe/compile-commands#3]
The compile_commands.json spec allows for the compile command to be in either 'command' (string) or 'arguments' (list of strings), but this tool doesn't handle the latter.

https://clang.llvm.org/docs/JSONCompilationDatabase.html

**Comment by qdewaghe** [comment]
Hi, I'm guessing this is what causes #2. 
I made a quick and dirty fix (not much time atm) that simply look if there is an `argument` field and joins it into `command`. Let me know if it works for you. I don't have a compilation database on hand that uses `arguments` to test thing properly. What tool generates such CDBs?

**Comment by hmoffatt** [comment]
My CDB is from bear - https://github.com/rizsotto/Bear

**Comment by hmoffatt** [comment]
Joining the arguments works as long as there are no spaces in them. I suspect this is why some tools might prefer the arguments list to the simple command string, as there's no need to split it and worry about quoting and spaces in arguments.

I think the safe way to do the join is using the new shlex.join function - https://docs.python.org/3/library/shlex.html

Also, it should probably delete arguments from the entry rather than setting it to null, as both are in the output now.

**Comment by qdewaghe** [comment]
Right, I should probably add an option to choose to output with `arguments` instead of `command` at some point just in case.

I did what you advised, I'll try to test it things out with Bear over the weekend.

**Comment by hmoffatt** [comment]
Thanks, this is working well now. I'm generating multiple compile_commands.json files with bear, merging and filtering with compile-commands and consuming with run-clang-tidy and it's all working.
